# user running simulations
user: "T.Gibson"

# unique run name (directory and results name)
# to include letters, numbers, underscores or dashes, no special characters
run_name: "Sim_7"

# seed number
seed: 2022

# number of simulations to run
num_sim: 10000

## SIMULATION PARAMETERS ---------------------------------------------------------------------
# number of years that sites are visited
num_years: 30

# number of sites to survey
num_sites: 100

# define distributions to use for introduction and establishment probabilities
# establishment and introduction is either: (1) 'random uniform' OR (2) 'equal uniform' OR (3) 'lognormal' 
# (4) 'exponential' OR (5) 'positive normal' (case insensitive)
establish_risk: "exponential"
intro_risk: "exponential"  # if normal majority of sites are intermediate risk

# probability of establishment, required if 'equal uniform' establish_risk
establish_prob: 0.8

# probability of introduction, required if 'equal uniform' intro_risk
intro_prob: 0.8

# frequency of site visits (e.g. 0.5 = once every 2 years)
mean_visit_rate: 1

# detection dynamic
# if "constant" the probabilty detection remains the same with time
# if "linear" the probability of detection increases with abundance
# if "threshold" the probability of detection is Prob_Below until abundance reaches a threshold value at which point it 
# increases to Prob_Above
detect_dynamic: "threshold"

# mean, minimum and maximum detection probability
det_prob: 0.1
det_prob_min: 0
det_prob_max: 0.8

# Number of seed sites can be 1 to num_sites
seed_n: 10

# Detection summary - if value of seed_n is greater than 1 this is used to get the time of detection from the multiple simulations
# can be first, last, mean, median
detect_summary: "last"

### Population Modelling Parameter
# These are required if detection_dynamic is "linear" or "threshold

# the starting initial population. For single sites a single value. For multiple sites a single value to define the possion distribution mean or a vector of values for each site. 
start_pop: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

# logical, indicating if a single start_pop value should be used as a mean value to draw from a possion distribution
start_possion: F

# numeric the finite rate of population increase.
pop_R: 1.5

# character defines the population growth model in "logistic" or "exponential"
growth_model: "logistic"

# numeric the carrying capacity at each site.
pop_cap: 100000 

# numeric the abundance required to increase the probability of detection by 0.01 if detection_dynmaic = linear
APrb: 500

# numeric the abundance which defines if a value of Prob_Below or Prob_Above is used for detection probability 
Abund_Threshold: 10000

# numeric the value given to the detection probability if abundance is below the threshold
Prob_Below: 0.1

# numeric the value given to the detection probability if abundance is at or above the threshold
Prob_Above: 0.8

## ADDITIONAL ANALYSES -----------------------------------------------------------------------
# logical stating whether sensitivity analysis and report should be generated
sensitivity_analysis: FALSE

# logical stating whether elasticity analysis and report should be generated
elasticity_analysis: FALSE

# percentage of change to test each parameters
elasticity_proportion: 0.1

defaults:
    name: "default"
    num_sites: 100
    num_years: 30
    establish_risk: "exponential"
    establish_prob: 0.8
    intro_prob: 0.8
    intro_risk: "exponential"
    mean_visit_rate: 1
    p_detection: 0.8
    max_p_detect: 0.9
    max_p_detect_elas: 1.0
    min_p_detect: 0.1
    detect_dynamic: "constant"
    seed_n: 1
    seed_n_elasticity: 10
    start_pop: 1
    start_possion: F
    pop_R: 2
    growth_model: "exponential"
    pop_cap: 500
    APrb: 10
    Abund_Threshold: 1000
    Prob_Below: 0.1
    Prob_Above: 0.8 
